version: "3.9"

services:
  db:
    image: docker.io/library/mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=devroot
      - MARIADB_DATABASE=appdb
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=devpass
    # volumes:
    #   - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -u root -p$MARIADB_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  dev:
    build:
      # context: "/home/daisuke/work/projects/references-flutter/.devcontainer"
      context: "${WORKSPACE}/.devcontainer"
      dockerfile: Dockerfile
    userns_mode: keep-id
    depends_on:
      db:
        condition: service_started
    environment:
      HOME: /home/vscode
    volumes:
      - type: bind
        source: "${WORKSPACE}"
        target: /workspace
    # Keep container alive under Podman (Debian base image would otherwise exit immediately).
    command: ["bash", "-lc", "while sleep 3600; do :; done"]

# volumes:
#   db_data: {}
